
@URL = http://localhost:3000/api

############################
######### Autores ##########
############################

###
GET {{URL}}/autores

###
GET {{URL}}/autores/3

###
POST {{URL}}/autores
Content-Type: application/json

{
  "nombre": "Carl Cox",
  "email": "carlcox@blog.com",
  "imagen": "https://www.animalbank.net/wp-content/uploads/2019/03/f4.jpg"
}

############################
########## Posts ###########
############################

###
GET {{URL}}/posts

### get post by idPost
GET {{URL}}/posts/29

### get posts by idAutor
GET {{URL}}/posts/byAutor/30

###
POST {{URL}}/posts
Content-Type: application/json

  {
    "titulo": "¿Techno o House? La Versatilidad del Sonido Carl Cox",
    "descripcion": "Discutiendo los límites de género en las sesiones de Cox, mostrando su habilidad para moverse fluidamente entre el House, el Techno y el Breakbeat.",
    "autores_id": 30,
    "categoria": "Análisis Musical"
  }