GET http://localhost:3000/api/autores

###
POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre": "Carl",
    "email": "carl@blog.com",
    "imagen": "https://www.animalbank.net/wp-content/uploads/2019/03/f4.jpg"
}

###
GET http://localhost:3000/api/posts